---

version: '3'

services:
  pnroit:
    container_name: pnroit
    build:
      context: .
      dockerfile: ./Dockerfile.pnroit
    volumes:
      - .:/application
    depends_on:
      - pnroit-mysql
    ports:
      - 3710:80
    tty: true
    stdin_open: true

  pnroit-mysql:
    container_name: pnroit-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      TZ: Europe/Moscow
    volumes:
      - ./docker/mysql-data:/var/lib/mysql
    ports:
      - 3711:3306

  pnroit-adminer:
    image: adminer
    restart: always
    ports:
      - 3712:8080